name: Build WASM
on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]
jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.61

      - name: Merge star catalog parts
        run: cat data/stars1.dat data/stars2.dat data/stars3.dat > data/stars.dat

      - name: Configure CMake
        run: emcmake cmake -B build -S .

      - name: Build
        run: cmake --build build

      - name: Upload WASM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kosmos-wasm
          path: |
            build/kosmos.wasm
            build/kosmos.js
